FROM ghcr.io/xac1/temp1:latest

# Copy source code to image
COPY tests /app

# add coverage
RUN apk add py3-coverage

# Run the application
CMD ["sh", "-c", "python3 main.py && python3 -m unittest test.py"]
