FROM ghcr.io/xac1/temp1:latest

# Copy source code to image
COPY tests /add

# add coverage
RUN apt-get install -y python3-coverage
# Run the application
CMD ["sh", "-c", "python3 connect_and_run.py && python3 -m unittest test.py"]
